### ISSUE TITLE
Entrega da etapa de início do laboratório - 19/08/2018.

### ISSUE THREAD

**Issue by lgnsparda** [lgnsparda/Laboratorio_Dinamica_dos_Fluidos-FGA-UnB#1]
Entrega da etapa de início do laboratório - 19/08/2018.

**Comment by gustavohyd** [comment]
### Relatório 01 - Grupo 14

- Integrantes:
  Pedro Henrique de Sousa Santos - 15/0144342
  Gustavo Henrique Yabuki Dubas - 15/0128649

- Tema:
  Efeito Bernoulli.

- Objetivo:
  Comprovar, experimentalmente, a existência do "Efeito Bernoulli". Utilizando o tubo de escoamento do laboratório de termofluidos, serão medidas as pressões antes e depois de um bocal.

- Escopo:
  Para executar o experimento, serão pesquisadas bases teóricas sobre o "Efeito Bernoulli". O experimento será executado no laboratório de termofluidos, utilizando o tubo de escoamento e medindo as pressões antes e depois de um bocal.

**Comment by Gustavo-saraiva** [comment]
RELATÓRIO 1 - GRUPO 8
Integrantes do grupo:
Beatriz Carolina - 16/0002958
Gustavo Saraiva - 16/0050537
Renato Nascimento - 16/0143551

Tema escolhido: Turbulência em fluidos 
Objetivo do experimento – O que será medido ou determinado no experimento;
A maioria dos sistemas reais os escoamentos são turbulentos e podem apresentar diversos níveis de turbulência. O objetivo desse experimento é o de analisar o grau de turbulência de escoamentos através do cálculo do número de Reynolds.
Escopo do experimento – Estabelecimento de tarefas mínimas para cumprir os objetivos do experimento;
Definição e conhecimento acerca da teoria básica da dinâmica de escoamento de fluidos;
Definição através de pesquisa de campo e exploratória para a obtenção e construção do material necessário para a realização do experimento;
Pesquisar qual a funcionalidade do número de Reynolds e como tal pode demonstrar características de um fluido;
Através da pesquisa sobre o número de Reynolds, escolher o(s) fluido(s) de pesquisa e realizar os experimentos de escoamento para analisarmos quais são as características de tal utilizando a teoria por trás do número de Reynolds. Além de concluir como este número pode ser utilizado na escolha de projetos ou missões, a partir da pesquisa experimental.

**Comment by ghcasari** [comment]
RELATÓRIO 1 - GRUPO 9

1 - Integrantes do grupo:
Gabriel Casari - 13/0009091
Bruno Martins - 14/0017682
Letícia Dias - 14/0149414

2 - Tema escolhido: Perda de Carga

3 - Objetivo do experimento – O que será medido ou determinado no experimento;
O objetivo do experimento consiste no cálculo da perda de carga no escoamento do fluido por meio da variação de pressão, decorrente do atrito com as paredes e turbulência do fluido.As medidas realizadas no experimento serão da diferença de pressão que existe na tubulação.

4 - Escopo do experimento – Estabelecimento de tarefas mínimas para cumprir os objetivos do experimento;

-Fundamentação teórica e pesquisa quanto à perda de carga, e suas respectivas causas.
-Desenvolvimento de metodologia para obtenção e medição dos dados no experimento.
-Conhecimentos e análise dos equipamentos de medição que serão utilizados no experimento.
-Utilização da tubulação para medição das pressões e cálculos para determinação da perda de carga.

**Comment by matheusmariano88** [comment]
## Relatório 01 - Grupo 02

### Integrantes
- Richard da Silva Francisco de Souza - 14/0091793
- Luyza Lorenna L. Lopes - 16/0135133
- Matheus de Avila Mariano - 16/0137896

### Tema

Experimentos em túnel de vento

### Objetivo do experimento

Medir o coeficiente de arrasto de um objeto(à determinar).

### Escopo do experimento

- Levantamento da teoria necessária para a realização do experimento;
- Levantamento de dados e variáveis necessários para o cálculo;
- Levantamento das forças devidas as ações estática e dinâmica do vento;
- Escolha do objeto a ser analisado no experimento em questão;
- Realização do experimento em si, com o túnel de vento do Laboratório de Termofluidos da FGA.
